# Generated by Django 6.0.3 on 2026-03-26 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('loopback_ip', models.GenericIPAddressField(unique=True)),
                ('model', models.CharField(max_length=50)),
                ('vendor', models.CharField(choices=[('huawei', 'Huawei'), ('cisco', 'Cisco'), ('juniper', 'Juniper')], max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('loopback_ip', models.GenericIPAddressField(unique=True)),
                ('model', models.CharField(max_length=50)),
                ('interface_sw', models.CharField(blank=True, max_length=50)),
                ('interface_rt', models.CharField(blank=True, max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='devices.router')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
