# Generated by Django 6.0.3 on 2026-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne_name', models.CharField(max_length=100)),
                ('ne_ip_address', models.CharField(blank=True, max_length=50)),
                ('ne_type', models.CharField(blank=True, max_length=100)),
                ('board_full_name', models.CharField(blank=True, max_length=100)),
                ('board_name', models.CharField(blank=True, max_length=100)),
                ('board_type', models.CharField(blank=True, max_length=100)),
                ('slot_id', models.CharField(blank=True, max_length=20)),
                ('hardware_version', models.CharField(blank=True, max_length=50)),
                ('software_version', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('board_status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('unknown', 'Unknown')], default='normal', max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('manufactured_on', models.CharField(blank=True, max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ne_name', 'board_full_name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne_name', models.CharField(max_length=100)),
                ('ne_type', models.CharField(blank=True, max_length=100)),
                ('port_full_name', models.CharField(blank=True, max_length=100)),
                ('port_name', models.CharField(blank=True, max_length=100)),
                ('port_type', models.CharField(blank=True, max_length=50)),
                ('port_rate', models.CharField(blank=True, max_length=20)),
                ('port_level', models.CharField(blank=True, max_length=10)),
                ('admin_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('oper_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('port_alias', models.CharField(blank=True, max_length=200)),
                ('port_description', models.CharField(blank=True, max_length=200)),
                ('port_ip_address', models.CharField(blank=True, max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ne_name', 'port_full_name'],
            },
        ),
        migrations.CreateModel(
            name='SFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne_name', models.CharField(max_length=100)),
                ('port_name', models.CharField(blank=True, max_length=100)),
                ('port_description', models.CharField(blank=True, max_length=200)),
                ('port_type', models.CharField(blank=True, max_length=50)),
                ('optical_type', models.CharField(blank=True, max_length=50)),
                ('rx_power', models.CharField(blank=True, max_length=20)),
                ('tx_power', models.CharField(blank=True, max_length=20)),
                ('rx_status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('unknown', 'Unknown')], default='normal', max_length=20)),
                ('tx_status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('unknown', 'Unknown')], default='normal', max_length=20)),
                ('speed', models.CharField(blank=True, max_length=20)),
                ('fiber_type', models.CharField(blank=True, max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('wavelength', models.CharField(blank=True, max_length=20)),
                ('transmission_distance', models.CharField(blank=True, max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SFP',
                'ordering': ['ne_name', 'port_name'],
            },
        ),
    ]
