# Generated by Django 6.0.3 on 2026-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_card_port_sfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='board_status',
            field=models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('unknown', 'Unknown')], default='normal', max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='hardware_version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='manufactured_on',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='software_version',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
