# Generated by Django 6.0.3 on 2026-04-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_card_board_status_alter_card_hardware_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
