# Generated by Django 6.0.3 on 2026-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_router_ssh_password_router_ssh_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ne_name', models.CharField(max_length=100)),
                ('ne_type', models.CharField(blank=True, max_length=100)),
                ('subboard_full_name', models.CharField(blank=True, max_length=200)),
                ('subboard_name', models.CharField(blank=True, max_length=100)),
                ('subboard_type', models.CharField(blank=True, max_length=100)),
                ('subrack_id', models.CharField(blank=True, max_length=20)),
                ('slot_number', models.CharField(blank=True, max_length=20)),
                ('subslot_number', models.CharField(blank=True, max_length=20)),
                ('hardware_version', models.CharField(blank=True, max_length=200)),
                ('software_version', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('subboard_status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('unknown', 'Unknown')], default='normal', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('manufactured_on', models.CharField(blank=True, max_length=200)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SubCard',
                'ordering': ['ne_name', 'subboard_full_name'],
            },
        ),
    ]
