from rest_framework import viewsets
from .models import MonthlyReport
from .serializers import MonthlyReportSerializer

class MonthlyReportViewSet(viewsets.ReadOnlyModelViewSet):
    """
    A viewset that provides default `list()` and `retrieve()` actions.
    Reports are generated by Celery, so we prevent frontend POST/DELETE requests.
    """
    queryset = MonthlyReport.objects.all()
    serializer_class = MonthlyReportSerializer
