# Generated by Django 6.0.3 on 2026-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_ip', models.GenericIPAddressField()),
                ('task_type', models.CharField(choices=[('backhaul', 'Backhaul Link'), ('b2b', 'B2B Link'), ('internet', 'Internet Service'), ('voip', 'VoIP Service'), ('mpls', 'MPLS'), ('vpn', 'VPN')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='queued', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
