# Generated by Django 6.0.3 on 2026-04-17 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_router_ssh_password_router_ssh_username'),
        ('provisioning', '0002_alter_provisioningtask_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthUpgrade',
            fields=[
                ('upgrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('interface', models.CharField(help_text='Interface name (e.g., GigabitEthernet0/0/1 or ge-0/0/1)', max_length=50)),
                ('vlan', models.CharField(blank=True, help_text='VLAN unit for Cisco/Juniper', max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('old_bandwidth_mbps', models.IntegerField(blank=True, help_text='Previous bandwidth in Mbps', null=True)),
                ('new_bandwidth_mbps', models.IntegerField(help_text='New bandwidth in Mbps')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_commands', models.TextField(help_text='CLI commands that were/will be executed')),
                ('execution_output', models.TextField(blank=True, help_text='SSH command output', null=True)),
                ('swan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('swan_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_upgrades', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_upgrades', to='devices.router')),
            ],
            options={
                'db_table': 'bandwidth_upgrades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'interface'], name='bandwidth_u_device__ccb6cf_idx'), models.Index(fields=['status'], name='bandwidth_u_status_603297_idx'), models.Index(fields=['created_at'], name='bandwidth_u_created_df4e66_idx')],
            },
        ),
    ]
