# Generated by Django 6.0.6 on 2026-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_bandwidthupgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningtask',
            name='script_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='provisioningtask',
            name='status',
            field=models.CharField(choices=[('queued', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('liberated', 'Libéré')], default='queued', max_length=20),
        ),
    ]
