# Generated by Django 6.0.6 on 2026-06-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_alter_bandwidthupgrade_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisioningtask',
            name='task_type',
            field=models.CharField(choices=[('backhaul', 'Backhaul Link'), ('b2b', 'B2B Link'), ('internet', 'Internet Service'), ('voip', 'VoIP Service'), ('mpls', 'MPLS'), ('l2vc', 'L2VC Service'), ('vpn', 'VPN'), ('configure_vlan', 'Configure VLAN'), ('firmware_upgrade', 'Firmware Upgrade'), ('push_acl', 'Push ACL')], max_length=20),
        ),
    ]
