
"""
Django settings for automation_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a%5#ya5@pdz&0mbv52v4r)i!iz*-=k+pkw1@=zn*i%^aw0axe8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
# Third-party
'rest_framework',
'django_filters',
'corsheaders',
# DRS 010 apps
'backhaul',
'b2b',
'devices',
'services',
'provisioning',
'monitoring',
'reporting',
'ai',
'inventory',
]

MIDDLEWARE = [
'corsheaders.middleware.CorsMiddleware', # doit être EN PREMIER
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
'http://localhost:4200', # Angular dev server (Windows)
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # ← add this line
# ── Celery + Redis ──
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
from celery.schedules import crontab

# ... your existing celery settings ...

CELERY_BEAT_SCHEDULE = {
    'generate-monthly-report-on-the-1st': {
        'task': 'reporting.tasks.generate_monthly_network_report',
        # Run at 00:05 AM on the 1st day of every month
        'schedule': crontab(minute=5, hour=0, day_of_month=1),
    },
}
# ── Django REST Framework ──
REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': [

],
'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
 'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
 # 'PAGE_SIZE': 300, #------------------------------------------
}

ROOT_URLCONF = 'automation_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'automation_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# settings.py
if 'test' in sys.argv:
    DATABASES['default']['TEST'] = {
        'NAME': 'test_drs010_fresh',  # brand new name, no conflict
    }
DATABASES = {
'default': {
'ENGINE': 'django.db.backends.postgresql',
'NAME': 'drs010_db',
'USER': 'drs010_user',
'PASSWORD': 'drs010pass',
'HOST': 'localhost',
'PORT': '5432',
}
}
# settings.py

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# L'URL publique pour accéder aux fichiers
MEDIA_URL = '/media/'

# Le dossier physique sur ton ordinateur/serveur
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
GROQ_API_KEY = "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"
