# Generated by Django 6.0.3 on 2026-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackhaulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('bandwidth', models.IntegerField(help_text='Mbps')),
                ('device_type', models.CharField(choices=[('huawei', 'Huawei VRP'), ('cisco', 'Cisco IOS'), ('juniper', 'Juniper JunOS')], default='huawei', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('active', 'Actif'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
