# Generated by Django 6.0.3 on 2026-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backhaul', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backhaullink',
            options={'ordering': ['alarm_severity', 'source_ne']},
        ),
        migrations.RenameField(
            model_name='backhaullink',
            old_name='created_at',
            new_name='imported_at',
        ),
        migrations.RenameField(
            model_name='backhaullink',
            old_name='name',
            new_name='sink_ne',
        ),
        migrations.RemoveField(
            model_name='backhaullink',
            name='bandwidth',
        ),
        migrations.RemoveField(
            model_name='backhaullink',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='backhaullink',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='backhaullink',
            name='status',
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='alarm_severity',
            field=models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='delay_time',
            field=models.IntegerField(blank=True, help_text='microseconds', null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='link_level',
            field=models.CharField(choices=[('1GE', '1 GigabitEthernet'), ('10GE', '10 GigabitEthernet'), ('100GE', '100 GigabitEthernet')], default='10GE', max_length=10),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='link_name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='link_rate',
            field=models.BigIntegerField(blank=True, help_text='bit/s', null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='link_type',
            field=models.CharField(choices=[('l2_link', 'L2 Link'), ('l3_link', 'L3 Link')], default='l2_link', max_length=20),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='remaining_bw_downstream',
            field=models.BigIntegerField(blank=True, help_text='Kbit/s', null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='remaining_bw_upstream',
            field=models.BigIntegerField(blank=True, help_text='Kbit/s', null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='sink_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='sink_port',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='sink_port_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='sink_port_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='source_ne',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='source_port',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='source_port_alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='source_port_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='backhaullink',
            name='user_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
