# Generated by Django 6.0.3 on 2026-04-16 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_alter_card_board_status_alter_card_hardware_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VRFService',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('internet', 'Internet'), ('voip', 'VoIP'), ('mpls', 'MPLS'), ('vpn', 'VPN')], max_length=20)),
                ('interface', models.CharField(max_length=50)),
                ('vrf_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('provisioned', 'Provisionné'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrf_services', to='devices.router')),
            ],
            options={
                'db_table': 'vrf_services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BandwidthUpgrade',
            fields=[
                ('upgrade_id', models.AutoField(primary_key=True, serialize=False)),
                ('interface', models.CharField(help_text='Interface physique (ex: GigabitEthernet0/0/1)', max_length=50)),
                ('vlan', models.CharField(blank=True, help_text='VLAN unit pour Cisco/Juniper', max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('old_bandwidth_mbps', models.IntegerField(blank=True, help_text='Ancienne bande passante en Mbps', null=True)),
                ('new_bandwidth_mbps', models.IntegerField(help_text='Nouvelle bande passante en Mbps')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('rollback', 'Rollback')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_commands', models.TextField(help_text='Commandes CLI générées')),
                ('execution_output', models.TextField(blank=True, help_text='Sortie des commandes', null=True)),
                ('swan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('swan_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_upgrades', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandwidth_upgrades', to='devices.router')),
            ],
            options={
                'db_table': 'bandwidth_upgrades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'interface'], name='bandwidth_u_device__ccb6cf_idx'), models.Index(fields=['status'], name='bandwidth_u_status_603297_idx'), models.Index(fields=['created_at'], name='bandwidth_u_created_df4e66_idx')],
            },
        ),
    ]
