# Generated by Django 6.0.3 on 2026-06-08 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bandwidthupgrade',
            name='bandwidth_u_device__ccb6cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='bandwidthupgrade',
            name='bandwidth_u_status_603297_idx',
        ),
        migrations.RemoveIndex(
            model_name='bandwidthupgrade',
            name='bandwidth_u_created_df4e66_idx',
        ),
        migrations.RemoveField(
            model_name='bandwidthupgrade',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bandwidthupgrade',
            name='device',
        ),
        migrations.DeleteModel(
            name='VRFService',
        ),
        migrations.DeleteModel(
            name='BandwidthUpgrade',
        ),
    ]
