# Generated by Django 6.0.3 on 2026-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=20, unique=True)),
                ('total_routers', models.IntegerField(default=0)),
                ('total_switches', models.IntegerField(default=0)),
                ('total_links', models.IntegerField(default=0)),
                ('critical_alarms_count', models.IntegerField(default=0)),
                ('provisioning_tasks_completed', models.IntegerField(default=0)),
                ('provisioning_tasks_failed', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/monthly/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
