# Generated by Django 6.0.3 on 2026-06-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyreport',
            old_name='provisioning_tasks_completed',
            new_name='b2b_services_activated',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='backhaul_upgrades_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='hardware_failures_recorded',
            field=models.IntegerField(default=0),
        ),
    ]
