# Generated by Django 6.0.3 on 2026-06-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_rename_provisioning_tasks_completed_monthlyreport_b2b_services_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='provisioning_tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
