# Generated by Django 6.0.3 on 2026-04-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Réf.')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('classification', models.CharField(max_length=100, verbose_name='Classification')),
                ('vendor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fournisseur')),
                ('stock_qte', models.IntegerField(default=0, verbose_name='Stock')),
                ('transfert_nbr_u', models.IntegerField(default=0, verbose_name='Transfert (Nbr. U)')),
                ('transfert_qte', models.IntegerField(default=0, verbose_name='Transfert (Qté)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['classification', 'name'],
            },
        ),
    ]
